apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: default
  name: express-dev
  labels:
    app: express-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: https://kubernetes.default.svc
  project: default
  source:
    path: resources
    repoURL: git@github.com:danielm-codefresh/argo-submodule.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
